# (C) Copyright 2021-2022 United States Government as represented by the Administrator of the
# National Aeronautics and Space Administration. All Rights Reserved.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

# --------------------------------------------------------------------------------------------------

# Setup and installation script
#
# Usage: "pip install --prefix=/path/to/install ."

# --------------------------------------------------------------------------------------------------

[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "swell"
version = "1.20.3"
authors = [{name = "NASA Global Modeling and Assimilation Office"}]
description = "Workflow suites, tasks and configuration for coupled data assimilation"
requires-python = ">=3.11"
classifiers = [
"Development Status :: 1 - Planning",
"Environment :: Console",
"Intended Audience :: Science/Research",
"Programming Language :: Python :: 3 :: Only",
"Licence :: OSI Approved :: Apache Software License",
"Natural Language :: English",
"Operating System :: OS Independent"
]

dependencies = [
    "click>=8.0.0",
    "jinja2>=3.0.3",
    "pyyaml>=6.0",
    "pycodestyle>=2.11.0",
    "numpy<2",
    "pandas>=1.4.0",
    "isodate>=0.5.4",
    "f90nml>=1.4.3",
    "questionary>=1.10.0",
    "h5py>=3.7.0",
    "flake8==6.1.0",
    "netCDF4",
    "ruamel.yaml==0.17.16",
    "xarray==2024.7.0"
]

[project.optional-dependencies]
github = [
    "click==8.1.5",
    "jinja2==3.1.2",
    "pyyaml==6.0.1",
    "pandas>=1.4.0",
    "numpy==1.26.0",
    "isodate==0.6.1",
    "f90nml==1.4.4",
    "questionary==1.10.0",
    "netCDF4==1.6.5"
]

[project.urls]
Repository = "https://github.com/geos-esm/swell"
Documentation = "https://geos-esm.github.io/swell/#/"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
swell = [
    'deployment/platforms/*/modules*',
    'deployment/platforms/*/*.yaml',
    'suites/**',
    'test/suite_tests/*.yaml',
    'test/jedi_configs/*.yaml',
    'configuration/**',
    'utilities/pinned_versions/*.yaml'
]

[project.scripts]
swell = "swell.swell:main"
cylc = "swell.cylc_swell:execute_cylc"

