databases:

  local:
    class: LocalDB
    root: ${R2D2_LOCAL_PATH}
    cache_fetch: false

  shared:
    class: LocalDB
    root: /discover/nobackup/drholdaw/R2D2DataStore/Shared
    cache_fetch: false

# when fetching data, in which order should the databases accessed?
fetch_order:
  - shared

# when storing data, in which order should the databases accessed?
store_order:
  - local

cache_name: local
