# (C) Copyright 2021- United States Government as represented by the Administrator of the
# National Aeronautics and Space Administration. All Rights Reserved.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.


# --------------------------------------------------------------------------------------------------

import os
from ruamel.yaml import YAML
import unittest

from swell.swell_path import get_swell_path
from swell.utilities.mock_jedi_config import mock_jedi_config
from swell.utilities.scripts.create_mock_configs import defaults_dict
from swell.utilities.test_cache import get_test_cache

# --------------------------------------------------------------------------------------------------


class JEDIConfigTest(unittest.TestCase):

    def runTest(self) -> None:

        '''Generates new jedi config mocks for all suites and compares them to previous versions.

        Comparison mocks are located under `src/swell/test/jedi_configs`. The intention of this
        test is to ensure changes to the jedi configs generated by swell are intentional. These
        mock files are run in a 'dry' mode, in that they do not fetch or check observations,
        and all filepaths are filled by placeholders. The JEDI configs can then be neatly checked
        for equivalence.

        It is expected that this test will fail when any change is made to JEDI, thus new mock
        files will need to be generated when changes are made. New mock files can be generated
        automatically by running `swell utility CreateMockConfigs`.
        '''

        for suite, defaults in defaults_dict.items():
            model = defaults['model']
            datetime = defaults['datetime']
            executable_type = defaults['executable_type']

            cache_location = get_test_cache()

            # Create the mock jedi config
            config_file = mock_jedi_config(suite, model, datetime, executable_type, cache_location)

            # Read the file
            yaml = YAML(typ='safe')
            with open(config_file, 'r') as f:
                config_dict = yaml.load(f)

            # Open the comparison yaml for the suite
            comparison_path = os.path.join(get_swell_path(), 'test', 'jedi_configs')
            comparison_config = os.path.join(comparison_path,
                                             f'jedi_{suite}_config.yaml')
            with open(comparison_config, 'r') as f:
                comparison_dict = yaml.load(f)

            if config_dict != comparison_dict:
                raise AssertionError(f'Rendered JEDI config for suite {suite}, {config_file} '
                                     f'did not match comparison version {comparison_config}. '
                                     'Please check the file diffs. If these differences '
                                     'are intentional, new mock test files can be generated using '
                                     '`swell utility CreateMockConfigs`')

# --------------------------------------------------------------------------------------------------
