# This is a basic workflow to help you get started with Actions

name: CI-test-workflow.yml

# Controls when the workflow will run
on:
  pull_request:
    branches: [develop]

defaults:
  run:
    shell: bash

jobs:
  CI-test-workflow:
    uses: GEOS-ESM/CI-workflows-test/.github/workflows/swell-workflow01.yml@main
          
