# This is a basic workflow to help you get started with Actions

name: Tier-1

# Controls when the workflow will run
on:
  pull_request:
    branches: [develop]

defaults:
  run:
    shell: bash

jobs:
  CodeBuild:
    uses: GEOS-ESM/CI-workflows-test/.github/workflows/swell-workflow01.yml@main
