name: Swell Code Testing

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  testsuite:
    name: Run swell coding testing
    runs-on: ubuntu-latest

    steps:

    # Clone the swell code
    - name: Clone swell repo
      uses: actions/checkout@v2
      with:
        lfs: true

    # Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    # Update conda
    - name: Update conda
      run: conda update -n base -c defaults conda

    # Install pip
    - name: Install pip
      run: conda install pip

    # Upgrade pip
    - name: Upgrade pip
      run: $CONDA/bin/pip3 install --upgrade pip

    # Install swell
    - name: Install swell and dependencies
      run: $CONDA/bin/pip3 install -v --no-cache-dir --use-deprecated=legacy-resolver -r requirements-github.txt --user .

    # Put swell executables in the path
    - name: Put swell in the path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Run the swell code tests
    - name: Run swell code tests
      run: swell test code_tests
