# Discover Nightly

name: discover-nightly

#on:
#  pull_request:
#    types: [opened, synchronize, reopened]

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,15,30,45 * * * *'

defaults:
  run:
    shell: bash

jobs:
  run-discover-nightly:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-discover-nightly.yml@main
