# Discover Nightly

name: discover-nightly

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  run-discover-nightly:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-workflow01.yml@main
  # uses: GEOS-ESM/CI-workflows/.github/workflows/swell-discover-nightly.yml@main
