# SWELL Discover Tier1 HOFX

name: swell-discover-tier1-hofx

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  
  swell-discover-tier1-hofx:
    if: ${{ github.event.label.name == 'run-ci-discover (authorized users)' }}
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-discover-tier1-hofx.yml@main
