# Tier-1 Workflows

name: Tier-1

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  CodeBuild:
    uses: GEOS-ESM/CI-workflows-test/.github/workflows/swell-workflow01.yml@main
