name: Test CI Applications (Discover)

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-test-apps-discover:
    uses: GEOS-ESM/CI-workflow/.github/workflows/swell-tier1_application_discover.yml@feature/check_hashes
