name: Tier 1 Applications Tests (Discover)

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-tier1-apps-discover:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-tier1_application_discover.yml@feature/ufo_tests
