name: Tier 2 Applications Tests (Discover)

on:
  workflow_dispatch:

#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  run-tier2-apps-discover:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-tier2_application_discover.yml@feature/ufo_tests
