name: Tier 2 Applications Tests (Discover)

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  run-discover-nightly:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-tier1_application_discover.yml@main
