name: Tier 1 Applications Tests (Discover)

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-discover-nightly:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-discover-nightly.yml@main
