name: Tier 1 Applications Tests (Discover)

on: []

defaults:
  run:
    shell: bash

jobs:

  tier1-application-discover:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-tier1_application_discover.yml@feature/ufo_tests
