# (C) Copyright 2021- United States Government as represented by the Administrator of the
# National Aeronautics and Space Administration. All Rights Reserved.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.


# --------------------------------------------------------------------------------------------------

import os
import re

from swell.utilities.comparisons import comparison_tags
from swell.tasks.base.task_base import taskBase

# --------------------------------------------------------------------------------------------------


class CompareJediCtests(taskBase):

    def parse_results(self, results_file) -> list:
        '''
        Read results from a file containing output from JEDI ctests,
        and parse to a list of failed tests

        Parameters:
        results_file: path to a file containing output from bundle ctests
                      (e.g. one generated by the RunJediCtests task)

        Returns:
        failed_tests: list of tests failed for the build
        '''

        with open(results_file, 'r') as f:
            lines = f.readlines()

        if len(lines) == 0:
            raise Exception(f'File {results_file} does not contain results')

        failed_tests = []

        for line in lines:
            if re.search('- .* \(Failed\)', line):  # noqa
                failed_tests.append(line.split('-')[1].split('(Failed)')[0].strip())

        failed_tests = list(set(failed_tests))

        return failed_tests

    def execute(self) -> None:

        # Paths to experiments to compare
        experiment_paths = self.config.comparison_experiment_paths()

        # Bundles to consider ctest results for
        bundles = self.config.bundles_to_run_ctests()

        # Attach tags to paths, if not present
        experiment_tag_paths = comparison_tags(experiment_paths, self.logger)

        experiment_tag_1 = list(experiment_tag_paths.keys())[0]
        experiment_tag_2 = list(experiment_tag_paths.keys())[1]

        experiment_path_1 = list(experiment_tag_paths.values())[0]
        experiment_path_2 = list(experiment_tag_paths.values())[1]
        print(experiment_path_1)
        # Paths to the ctest results rendered by the RunJediCtests task
        ctest_path_1 = os.path.join(os.path.dirname(experiment_path_1), 'build-intel-release', 'ctests')
        ctest_path_2 = os.path.join(os.path.dirname(experiment_path_2), 'build-intel-release', 'ctests')

        # Dict tracking all test results
        results_dict = {}

        for bundle in bundles:
            ctest_file_1 = os.path.join(ctest_path_1, f'{bundle}.txt')
            ctest_file_2 = os.path.join(ctest_path_2, f'{bundle}.txt')

            # Parse for failed tests
            failed_results_1 = self.parse_results(ctest_file_1)
            failed_results_2 = self.parse_results(ctest_file_2)

            results_dict[bundle] = {}

            # Track which tests have failed for both builds
            for test in failed_results_1:
                if test not in results_dict[bundle].keys():
                    results_dict[bundle][test] = {experiment_tag_2: 'Pass'}
                results_dict[bundle][test][experiment_tag_1] = 'Fail'
                results_dict[bundle][test]['width'] = len(test)

            for test in failed_results_2:
                if test not in results_dict[bundle].keys():
                    results_dict[bundle][test] = {experiment_tag_1: 'Pass'}
                results_dict[bundle][test][experiment_tag_2] = 'Fail'
                results_dict[bundle][test]['width'] = len(test)

        # Whether the same number of tests pass
        passed = True

        # Format the string for readable output
        results_str = 'JEDI CTest Results Comparison\n'
        results_str += f'{experiment_tag_1}: {experiment_path_1}\n'
        results_str += f'{experiment_tag_2}: {experiment_path_2}\n\n'

        width_col_1 = max(len('Fail'), len(experiment_tag_1)) + 2
        width_col_2 = max(len('Fail'), len(experiment_tag_2)) + 2

        for bundle in bundles:
            max_width = max(len(bundle), max([results_dict[bundle][test]['width']
                                              for test in results_dict[bundle]])) + 2
            results_str += bundle + ' ' * (max_width - len(bundle))
            results_str += experiment_tag_1 + ' ' * (width_col_1 - len(experiment_tag_1))
            results_str += experiment_tag_2 + ' ' * (width_col_2 - len(experiment_tag_2))
            results_str += '\n'

            # Specify if all tests have passed
            if len(results_dict[bundle].keys()) == 0:
                results_str += 'All tests passed.\n'

            for test in results_dict[bundle].keys():
                results_str += test + ' ' * (max_width - len(test))
                result_1 = results_dict[bundle][test][experiment_tag_1]
                result_2 = results_dict[bundle][test][experiment_tag_2]
                if result_1 != result_2:
                    passed = False
                results_str += result_1 + ' ' * (width_col_1 - len(result_1))
                results_str += result_2 + ' ' * (width_col_2 - len(result_2))
                results_str += '\n'

            results_str += '\n'

        self.logger.info(results_str)

        out_path = os.path.join(self.experiment_path(), 'ctests')
        os.makedirs(out_path, exist_ok=True)
        with open(os.path.join(out_path, 'ctest_comparison.txt'), 'w') as f:
            f.write(results_str)

        if not passed:
            # Send the result to job.err as well
            self.logger.error(results_str)
            raise Exception(f'Differing tests passed between experiments')


# --------------------------------------------------------------------------------------------------
